
export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART";
export const EMPTY_CART="EMPTY_CART";
export const PRODUCT_LIST=" PRODUCT_LIST";
export const SET_PRODUCT_LIST='SET_PRODUCT_LIST';
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const SET_PRODUCT_LIST_ERROR='SET_PRODUCT_LIST_ERROR';
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const  SET_PRODUCT_LIST_LOADING="SET_PRODUCT_LIST_LOADING";